-------------------------------------------------------------------------------

CHIBO 2024

An attempt to static calculate the forces in (x,y,z) at all the suspension pickup points for various roll/jounce effects

18.12.2024: Created

03.01.2025: Outboard points calc working, moved functions to susprog.py and added loop 
05.01.2025: Added jounce updater for the inner points and included in susprog.py

-------------------------------------------------------------------------------

In [1]:
import numpy as np
import pandas as pd
from scipy.optimize import minimize

import plotly.graph_objects as go
import matplotlib.pyplot as plt

import susprog                      # Python file containing the equations for the loop 

In [2]:
# Declare motions for evaluation

# Define maximum roll and jounce inputs
body_roll = -5  # Maximum roll angle in degrees
body_jounce = 0.00  # Maximum jounce in meters (5 cm = 0.05)

# Generate roll and jounce motion inputs
roll_angles = np.linspace(0, np.radians(body_roll), 2)  # 0 to max roll angle in 100 steps
jounce_displacements = np.linspace(0, body_jounce, 2)  # 0 to max jounce in 100 steps

In [3]:
# Suspension pickup points
#        x      y    z
upper_a_arm = np.array([
    [0.0015, 0.5065, 0.315],  # Outer point (converted from mm to m)
    [-0.135, 0.240, 0.220],   # Inner leading point
    [0.180, 0.255, 0.255]     # Inner trailing point
])

lower_a_arm = np.array([
    [-0.0175, 0.519, 0.137],  # Outer point
    [-0.180, 0.165, 0.087],   # Inner leading point
    [0.180, 0.170, 0.087]     # Inner trailing point
])

tie_rod = np.array([
    [0.060, 0.515, 0.160],  # Outer point
    [0.070, 0.195, 0.100]   # Inner point
])

tire_cop = np.array([-0.005, 0.525, 0])  # Converted from mm to m
force_vector = np.array([50, 500, -2000.0])  # Force at the CoP (N)


In [4]:
# Calculate lengths for upper and lower A-arms and tie rod
upper_lengths = [
    np.linalg.norm(upper_a_arm[1] - upper_a_arm[0]),  # Upper outer to inner leading
    np.linalg.norm(upper_a_arm[2] - upper_a_arm[0]),  # Upper outer to inner trailing
    np.linalg.norm(upper_a_arm[0] - lower_a_arm[0])   # Upper outer to lower outer
]

lower_lengths = [
    np.linalg.norm(lower_a_arm[1] - lower_a_arm[0]),  # Lower outer to inner leading
    np.linalg.norm(lower_a_arm[2] - lower_a_arm[0]),  # Lower outer to inner trailing
    np.linalg.norm(lower_a_arm[0] - tire_cop)         # Lower outer to tire center of pressure
]

tie_length = [
    np.linalg.norm(tie_rod[1] - tie_rod[0]),          # Tie rod outer to inner leading
    np.linalg.norm(upper_a_arm[0] - tie_rod[0]),      # Tie rod outer to upper outer
    np.linalg.norm(lower_a_arm[0] - tie_rod[0])       # Tie rod outer to lower outer
]

In [ ]:
def plot_suspension_interactive(upper, lower, upper_rot, low_rot, tie, tie_rot, cop):
    fig = go.Figure()

    # Upper A-arm
    fig.add_trace(go.Scatter3d(
        x=[upper[0, 0], upper[1, 0]], y=[upper[0, 1], upper[1, 1]], z=[upper[0, 2], upper[1, 2]],
        mode='lines+markers',
        name='Upper A-arm (Outer to Inner Leading)',
        marker=dict(size=6, color='blue'),
        line=dict(color='blue', width=2)
    ))
    fig.add_trace(go.Scatter3d(
        x=[upper[0, 0], upper[2, 0]], y=[upper[0, 1], upper[2, 1]], z=[upper[0, 2], upper[2, 2]],
        mode='lines+markers',
        name='Upper A-arm (Outer to Inner Trailing)',
        line=dict(color='blue', width=2)
    ))
    fig.add_trace(go.Scatter3d(
        x=[upper[1, 0], upper[2, 0]], y=[upper[1, 1], upper[2, 1]], z=[upper[1, 2], upper[2, 2]],
        mode='lines',
        name='Upper A-arm (Inner leading to Inner Trailing)',
        line=dict(color='blue', width=2, dash='dot')
    ))
    # Rotated Upper A-arm
    fig.add_trace(go.Scatter3d(
        x=[upper_rot[0, 0], upper_rot[1, 0]], y=[upper_rot[0, 1], upper_rot[1, 1]], z=[upper_rot[0, 2], upper_rot[1, 2]],
        mode='lines+markers',
        name='Upper A-arm (Rot Outer to Inner Leading)',
        marker=dict(size=6, color='purple'),
        line=dict(color='purple', width=2)
    ))
    fig.add_trace(go.Scatter3d(
        x=[upper_rot[0, 0], upper_rot[2, 0]], y=[upper_rot[0, 1], upper_rot[2, 1]], z=[upper_rot[0, 2], upper_rot[2, 2]],
        mode='lines+markers',
        name='Upper A-arm (Rot Outer to Inner Trailing)',
        marker=dict(size=6, color='purple'),
        line=dict(color='purple', width=2)
    ))
    
    fig.add_trace(go.Scatter3d(
        x=[upper_rot[1, 0], upper_rot[2, 0]], y=[upper_rot[1, 1], upper_rot[2, 1]], z=[upper_rot[1, 2], upper_rot[2, 2]],
        mode='lines',
        name='Upper A-arm (Rot Inner leading to Inner Trailing)',
        line=dict(color='purple', width=2, dash='dot')
    ))
    
    # Lower A-arm
    fig.add_trace(go.Scatter3d(
        x=[lower[0, 0], lower[1, 0]], y=[lower[0, 1], lower[1, 1]], z=[lower[0, 2], lower[1, 2]],
        mode='lines+markers',
        name='Lower A-arm (Outer to Inner Leading)',
        marker=dict(size=6, color='green'),
        line=dict(color='green', width=2)
    ))
    fig.add_trace(go.Scatter3d(
        x=[lower[0, 0], lower[2, 0]], y=[lower[0, 1], lower[2, 1]], z=[lower[0, 2], lower[2, 2]],
        mode='lines+markers',
        name='Lower A-arm (Outer to Inner Trailing)',
        line=dict(color='green', width=2)
    ))
    fig.add_trace(go.Scatter3d(
        x=[lower[1, 0], lower[2, 0]], y=[lower[1, 1], lower[2, 1]], z=[lower[1, 2], lower[2, 2]],
        mode='lines',
        name='lower A-arm (Inner leading to Inner Trailing)',
        line=dict(color='green', width=2, dash='dot')
    ))
    
    # Rotated Lower A-arm
    fig.add_trace(go.Scatter3d(
        x=[low_rot[0, 0], low_rot[1, 0]], y=[low_rot[0, 1], low_rot[1, 1]], z=[low_rot[0, 2], low_rot[1, 2]],
        mode='lines+markers',
        name='lower rotated A-arm (Outer to Inner Leading)',
        marker=dict(size=6, color='cyan'),
        line=dict(color='cyan', width=2)
    ))
    fig.add_trace(go.Scatter3d(
        x=[low_rot[0, 0], low_rot[2, 0]], y=[low_rot[0, 1], low_rot[2, 1]], z=[low_rot[0, 2], low_rot[2, 2]],
        mode='lines+markers',
        name='lower rotated A-arm (Outer to Inner Trailing)',
        line=dict(color='cyan', width=2)
    ))
    fig.add_trace(go.Scatter3d(
        x=[low_rot[1, 0], low_rot[2, 0]], y=[low_rot[1, 1], low_rot[2, 1]], z=[low_rot[1, 2], low_rot[2, 2]],
        mode='lines',
        name='lower rotated A-arm (Inner leading to Inner Trailing)',
        line=dict(color='cyan', width=2, dash='dot')
    ))

    # Tie rod
    fig.add_trace(go.Scatter3d(
        x=[tie[0, 0], tie[1, 0]], y=[tie[0, 1], tie[1, 1]], z=[tie[0, 2], tie[1, 2]],
        mode='lines+markers',
        name='Tie Rod',
        marker=dict(size=6, color='red'),
        line=dict(color='red', width=2)
    ))

    # Rotated Tie rod
    fig.add_trace(go.Scatter3d(
        x=[tie_rot[0, 0], tie_rot[1, 0]], y=[tie_rot[0, 1], tie_rot[1, 1]], z=[tie_rot[0, 2], tie_rot[1, 2]],
        mode='lines+markers',
        name='Rotated Tie Rod',
        marker=dict(size=6, color='orange'),
        line=dict(color='orange', width=2)
    ))
    # Tire CoP
    fig.add_trace(go.Scatter3d(
        x=[cop[0]], y=[cop[1]], z=[cop[2]],
        mode='markers',
        name='Tire CoP',
        marker=dict(size=8, color='orange')
    ))

    # Set axis labels
    fig.update_layout(
        title="Interactive Suspension Geometry (Corrected Connections)",
        scene=dict(
            xaxis_title="X (m)",
            yaxis_title="Y (m)",
            zaxis_title="Z (m)"
        )
    )

    fig.show()

# Example usage
plot_suspension_interactive(upper_a_arm, lower_a_arm, upper_modified, lower_modified, tie_rod, tierod_modified, tire_cop)


In [5]:
# Run simulation

# Columns: [roll_angle (rad), jounce (m), suspension_positions (1x9), rc_x, rc_y, rc_z]
results = np.zeros((len(roll_angles), 37))  # 100 rows, 33 columns
rc, geo_roll_centre = susprog.calculate_roll_center(upper_a_arm, lower_a_arm, tire_cop)

# Set rotation point to origin
# rc = [0,0,0]

# Roll axis (example: x-axis)
roll_axis = np.array([1, 0, 0])

# Initialize rotated arms as a copy of the original
upper_modified = upper_a_arm.copy()
lower_modified = lower_a_arm.copy()
tierod_modified = tie_rod.copy()

# Loop through each roll and jounce input
for i, (roll_angle, jounce_disp) in enumerate(zip(roll_angles, jounce_displacements)):
    # Step 1: Rotate and jounce the inner points of the arms and tie rod
    upper_modified = susprog.rotate_points(upper_a_arm, rc, roll_axis, roll_angle, jounce_disp)
    #upper_modified = susprog.jounce_innerpoints(upper_a_arm, upper_modified, jounce_disp)

    lower_modified = susprog.rotate_points(lower_a_arm, rc, roll_axis, roll_angle, jounce_disp)
    #lower_modified = susprog.jounce_innerpoints(lower_a_arm, lower_modified, jounce_disp)
    
    tierod_modified = susprog.rotate_points(tie_rod, rc, roll_axis, roll_angle, jounce_disp)
    #tierod_modified = susprog.jounce_innerpoints(tie_rod, tierod_modified, jounce_disp)

    # Step 3: Update outer points of lower, upper, and tie rod
    # Lower A-arm
    points_temp = np.vstack((lower_modified, tire_cop))
    lower_modified[0:1] = susprog.solve_outer_position(points_temp, lower_lengths)
    del points_temp

    # Upper A-arm
    points_temp = np.vstack((upper_modified, lower_modified[0:]))
    upper_modified[0:1] = susprog.solve_outer_position(points_temp, upper_lengths)
    del points_temp

    # Tie rod
    points_temp = np.vstack((tierod_modified, upper_modified[0:1], lower_modified[0:1]))
    tierod_modified[0:1] = susprog.solve_outer_position(points_temp, tie_length)
    del points_temp


    # Step 4: Calculate the new roll center
    # rc, geo_roll_centre = susprog.calculate_roll_center(upper_modified, lower_modified, tire_cop)
    # Flatten geometry data dictionary into a list
    geometry_values = [
        geo_roll_centre['instant_center_2d'][0],  # Instant center x
        geo_roll_centre['instant_center_2d'][1],  # Instant center z
        geo_roll_centre['swing_arm_length'],      # Swing arm length
        geo_roll_centre['upper_arm_angle'],       # Upper arm angle
        geo_roll_centre['lower_arm_angle'],       # Lower arm angle
        *geo_roll_centre['upper_normal'],         # Upper plane normal (3 components)
        *geo_roll_centre['lower_normal']          # Lower plane normal (3 components)
    ]
    
    trails = susprog.trail_calc(upper_modified, lower_modified, tire_cop)

    # Step 5: Store the results
    results[i, 0] = roll_angle  # Roll angle (in radians)
    results[i, 1] = jounce_disp  # Jounce displacement
    results[i, 2:11] = lower_modified.flatten()  # Lower A-arm positions (3x3 -> 1x9)
    results[i, 11:20] = upper_modified.flatten()  # Upper A-arm positions (3x3 -> 1x9)
    results[i, 20:23] = rc  # Roll center (1x3)
    results[i, 23] = geo_roll_centre['instant_center_2d'][0]  # IC x
    results[i, 24] = geo_roll_centre['instant_center_2d'][1]  # IC z
    results[i, 25] = geo_roll_centre['swing_arm_length']      # Swing arm length
    results[i, 26] = geo_roll_centre['upper_arm_angle']       # Upper arm angle
    results[i, 27] = geo_roll_centre['lower_arm_angle']       # Lower arm angle
    results[i, 28:31] = geo_roll_centre['upper_normal']       # Upper plane normal (x, y, z)
    results[i, 31:34] = geo_roll_centre['lower_normal']       # Lower plane normal (x, y, z)
    results[i, 34:37] = trails # Steering axis==> tire cop (1x3)

del i

# Convert results to a DataFrame for easier visualization and saving
column_names = [
    "roll_angle", "jounce", 
    "lower_outer_x", "lower_outer_y", "lower_outer_z", 
    "lower_inner1_x", "lower_inner1_y", "lower_inner1_z", 
    "lower_inner2_x", "lower_inner2_y", "lower_inner2_z",
    "upper_outer_x", "upper_outer_y", "upper_outer_z", 
    "upper_inner1_x", "upper_inner1_y", "upper_inner1_z", 
    "upper_inner2_x", "upper_inner2_y", "upper_inner2_z",
    "rc_x", "rc_y", "rc_z",
    "ic_x", "ic_z", "sal", "upper_angle", "lower_angle",  # Geometry data
    "upper_normal_x", "upper_normal_y", "upper_normal_z",  # Upper plane normal
    "lower_normal_x", "lower_normal_y", "lower_normal_z",   # Lower plane normal
    "Steering_trail_x", "Scrub_radius_y"
]
results_df = pd.DataFrame(results, columns=column_names)

# Save the results as a CSV file (optional)
results_df.to_csv("suspension_simulation_results.csv", index=False)

# Display the first few rows
#print(results_df.head())


In [6]:
# Extract the initial and final suspension points from the results
lower_initial = results[0, 2:11].reshape(3, 3)  # First row, lower A-arm (3x3)
upper_initial = results[0, 11:20].reshape(3, 3)  # First row, upper A-arm (3x3)

lower_final = results[-1, 2:11].reshape(3, 3)  # Last row, lower A-arm (3x3)
upper_final = results[-1, 11:20].reshape(3, 3)  # Last row, upper A-arm (3x3)

# Extract roll centers
rc_initial = results[0, 20:23]  # Initial roll center
rc_final = results[-1, 20:23]  # Final roll center

# Create a 3D scatter plot
fig = go.Figure()

# Add initial lower A-arm points
fig.add_trace(go.Scatter3d(
    x=lower_initial[:, 0], y=lower_initial[:, 1], z=lower_initial[:, 2],
    mode='markers+lines',
    marker=dict(size=5, color='blue'),
    name='Lower A-arm (Initial)'
))

# Add final lower A-arm points
fig.add_trace(go.Scatter3d(
    x=lower_final[:, 0], y=lower_final[:, 1], z=lower_final[:, 2],
    mode='markers+lines',
    marker=dict(size=5, color='red'),
    name='Lower A-arm (Final)'
))

# Add initial upper A-arm points
fig.add_trace(go.Scatter3d(
    x=upper_initial[:, 0], y=upper_initial[:, 1], z=upper_initial[:, 2],
    mode='markers+lines',
    marker=dict(size=5, color='green'),
    name='Upper A-arm (Initial)'
))

# Add final upper A-arm points
fig.add_trace(go.Scatter3d(
    x=upper_final[:, 0], y=upper_final[:, 1], z=upper_final[:, 2],
    mode='markers+lines',
    marker=dict(size=5, color='orange'),
    name='Upper A-arm (Final)'
))

# Add roll center points
fig.add_trace(go.Scatter3d(
    x=[rc_initial[0], rc_final[0]],
    y=[rc_initial[1], rc_final[1]],
    z=[rc_initial[2], rc_final[2]],
    mode='markers+lines',
    marker=dict(size=8, color='purple'),
    name='Roll Center'
))

# Configure the layout
fig.update_layout(
    scene=dict(
        xaxis_title='X-axis (m)',
        yaxis_title='Y-axis (m)',
        zaxis_title='Z-axis (m)'
    ),
    title="3D Suspension Geometry (Initial vs. Final)",
    legend=dict(x=0.1, y=0.9)
)

# Show the figure
fig.show()

# Print the initial and final points
print("Initial Lower A-arm Points:\n", lower_initial)
print("Final Lower A-arm Points:\n", lower_final)

print("Initial Upper A-arm Points:\n", upper_initial)
print("Final Upper A-arm Points:\n", upper_final)

print("Initial Roll Center:", rc_initial)
print("Final Roll Center:", rc_final)

Initial Lower A-arm Points:
 [[-0.0175  0.519   0.137 ]
 [-0.18    0.165   0.087 ]
 [ 0.18    0.17    0.087 ]]
Final Lower A-arm Points:
 [[-0.01755384  0.52852055  0.13704425]
 [-0.18        0.17313787  0.09924087]
 [ 0.18        0.17811884  0.0988051 ]]
Initial Upper A-arm Points:
 [[ 0.0015  0.5065  0.315 ]
 [-0.135   0.24    0.22  ]
 [ 0.18    0.255   0.255 ]]
Final Upper A-arm Points:
 [[-2.97215490e-04  5.28435927e-01  3.15686445e-01]
 [-1.35000000e-01  2.59444187e-01  2.25198089e-01]
 [ 1.80000000e-01  2.77437558e-01  2.58757567e-01]]
Initial Roll Center: [ 0.00000000e+00  3.09250000e-01 -7.35029077e-05]
Final Roll Center: [ 0.00000000e+00  3.09250000e-01 -7.35029077e-05]


In [27]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=results_df["roll_angle"],
        y=results_df["rc_y"],
        mode='lines',
        marker=dict(color='red'),
        name='Roll Centre Location, Y',
        yaxis='y'  # Explicitly associate this trace with the primary y-axis
    )
)

# Add the second trace for "rc_z" on the secondary y-axis
fig.add_trace(
    go.Scatter(
        x=results_df["roll_angle"],
        y=results_df["rc_z"],
        mode='lines',
        marker=dict(color='orange'),
        name='Roll Centre Location, Z',
        yaxis='y2'  # Explicitly associate this trace with the secondary y-axis
    )
)

# Update layout to add a secondary y-axis
fig.update_layout(
    title='Roll Centre Location',
    xaxis=dict(title='Roll Angle (radians)'),
    yaxis=dict(
        title='RC Location, Y (m)',
        titlefont=dict(color='red'),
        tickfont=dict(color='red')
    ),
    yaxis2=dict(
        title='RC Location, Z (m)',
        titlefont=dict(color='orange'),
        tickfont=dict(color='orange'),
        anchor='x',
        overlaying='y',
        side='right'  # Place the secondary y-axis on the right side
    ),
    legend=dict(x=0.5, y=-0.2, orientation='h')  # Adjust legend position if needed
)

# Show the figure
fig.show()

In [14]:
def trail_calc(upper_points, lower_points, cop):
    
    # Import the outer joint points of the suspension system
    
    # Lower outer point
    p0 = lower_points[0,:]
    # Upper outer point
    p1 = upper_points[0,:]
    
    
    # Calculate the vector
    v = p1 - p0
    tz = -p0[2]/(p1[2]-p0[2])
    x0 = p0[0] + tz*(p1[0]-p0[0])
    y0 = p0[1] + tz*(p1[1]-p0[1])
    z0 = 0
    
    trails = np.array([[x0, y0, z0]])
    
    return trails

trails_out = trail_calc(upper_a_arm, lower_a_arm, tire_cop)
print(trails_out)


[[-0.0321236   0.52862079  0.        ]]
